name: dyslexiease
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png        # Your app icon (from the SplashScreen)
    - assets/teacher.png     # Your mascot image
    - assets/pdf.png         # PDF icon
    - assets/camera.png      # Camera icon
    - assets/note.png        # Note icon
    - assets/bot.png         # Bot icon
    - assets/programmer.png  #scan pdf mascot
    - assets/photographer.png #scan picture mascot

  fonts:
    - family: OpenDyslexic  # The name you'll use in your code
      fonts:
        - asset: fonts/OpenDyslexic-Regular.otf
        - asset: fonts/OpenDyslexic-Bold.otf
          weight: 700  # or FontWeight.bold
        - asset: fonts/OpenDyslexic-Italic.otf
          style: italic